import Head from "next/head";
import Login from "@/pages/login/Login";
import { Toaster } from "react-hot-toast";
import { UseWrapper } from "../hooks/useContext";
import Link from "next/link";
import Thoughts from "./thoughts/Thoughts";
import ProtectedComponents from "@/components/auth/ProtectedComponents";
import Router from "next/router";
import Navbar from "@/components/Navbar";

export default function Home() {
  const logOutHandler = () => {
    localStorage.removeItem("dt-token");
    Router.push("/login");
  };
  return (
    <>
      <Head>
        <title>Daily Thoughts Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=""></main>
    </>
  );
}
