import Head from "next/head";
import Login from "@/components/auth/Login";
import { Toaster } from "react-hot-toast";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Toaster Component*/}
      <Toaster position="top-center" reverseOrder={false} />
      <h1 className="text-3xl text-center">Daily Thoughts</h1>
      <main className="flex justify-center">
        <Login />
      </main>
    </>
  );
}
